on:
  push:
    branches:
      - deploy

name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: files.000webhost.com
        FTP_USERNAME: my-simple-blog
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: public_html
        ARGS: --delete --verbose
        # --delete arg will delete files on the server if you've deleted them in git
